### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/ohsome-qgis-plugin#11]
Find a nice and suitable logo.

At the moment the generic QGIS development icon is used, which isn't pretty exciting.

Find the logo here: [Current Logo](https://github.com/GIScience/ohsome-qgis-plugin/blob/main/OhsomeQgis/gui/img/icon_ohsome.png)

**Comment by SlowMo24** [comment]
What about the HeiGit icon 
![image](https://user-images.githubusercontent.com/12476914/126173270-2a7e6c8d-77ee-4539-859f-dad61de91630.png)
or a subpart from the Ohsome-logo like
![image](https://user-images.githubusercontent.com/12476914/126173120-e9e99c76-adf1-4b89-886a-49b049c67f31.png)

**Comment by SlowMo24** [comment]
together with the logo and the renaming in #10 we might reconsider the location. Currently it is at Web toolbar (same location as QuickMapService, ORSTools, OSMInfo, AnimateOSM) while QuickOSM for example is at Vector toolbar.

**Comment by joker234** [comment]
You could use a [favicon-like version of the HeiGIT logo](https://heigit.org/wp-content/uploads/2018/01/favicon.png) until we find something else.
