### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by koebi** [GIScience/ohsome-qgis-plugin#60]
After reviewing the UI in [the qgis-like-output branch](https://github.com/GIScience/ohsome-qgis-plugin/tree/qgis-like-output), the following possible improvements came up:

- [x] Add header with general Info and Links (as before)
- [x] left-align `OSM type` (otherwise it feels a bit restless…)
- [x] `Measure` should be outside of `simple`, it's used for advanced as well
- [x] `Years - Months - Days` is a bit unclear - is this the Period for the Time interval below? If so, reorder and add title
- [x] What is `keep geometry less` in the advanced parameters
- [x] Rename `harmon. geom` to `harmon geom in output` since it only affects output
- [x] sort advanced parameters to the bottom
- [x] The option to add multiple point or polygon layers seems a bit unnecessary and can be dropped
- [x] Centroids get deleted once you click "+" again. These should stay, the API even supports multiple radii :)
- [x] any provider change issues a metadata request. This results in a lot of them. Can this be changed only if something in the provider settings changes?
- [x] if a layer contains a lot of points, the log gets rather long. could we add truncation to the geometry part in the log? Everything else is super helpful though!
- [x] if no output is given, a temporary layer should be produced

**Comment by Merydian** [comment]
`keep geometry less` applies the dict.pop() method on the dictionary created from the response geojson, with "Feature" as an argument. This, when checked, results in the output of an additional table *without* geometry, containing the same data as the usual output file.

**Comment by Merydian** [comment]
The branch [qgis-like-input](https://github.com/GIScience/ohsome-qgis-plugin/tree/qgis-like-input) solves: *The option to add multiple point or polygon layers seems a bit unnecessary and can be dropped* by taking input by selecting a layer, as in any other QGis tool. This dismisses the existing *Centroids* input option.  

What is the preferred option?

**Comment by koebi** [comment]
> `keep geometry less` applies the dict.pop() method on the dictionary created from the response geojson, with "Feature" as an argument. This, when checked, results in the output of an additional table _without_ geometry, containing the same data as the usual output file.

Then this could maybe be called "also save only data" or something similar.
I think the space for a more "lengthy" name is there, and there should be the possiblity to add a "comment" that only gets shown on mouseover.

**Comment by koebi** [comment]
> The branch [qgis-like-input](https://github.com/GIScience/ohsome-qgis-plugin/tree/qgis-like-input) solves: _The option to add multiple point or polygon layers seems a bit unnecessary and can be dropped_ by taking input by selecting a layer, as in any other QGis tool. This dismisses the existing _Centroids_ input option.
> 
> What is the preferred option?

Is it possible to keep the Centroids-option and have all other layer inputs as QGIS usually does?
If not, I'd like @mcauer and/or @joker234  to comment on this, since they have a better intuition on what will be more useful to our users.

**Comment by Merydian** [comment]
Regarding: *if a layer contains a lot of points, the log gets rather long. could we add truncation to the geometry part in the log?*: 
I assume we are talking about the View'->'Panels'->'Log Messages' log? From the documentation it seems that this was intentionally kept to full length for debugging reasons. Should we add truncation anyways?

**Comment by Merydian** [comment]
> > The branch [qgis-like-input](https://github.com/GIScience/ohsome-qgis-plugin/tree/qgis-like-input) solves: _The option to add multiple point or polygon layers seems a bit unnecessary and can be dropped_ by taking input by selecting a layer, as in any other QGis tool. This dismisses the existing _Centroids_ input option.
> > What is the preferred option?
> 
> Is it possible to keep the Centroids-option and have all other layer inputs as QGIS usually does? If not, I'd like @mcauer and/or @joker234 to comment on this, since they have a better intuition on what will be more useful to our users.

I suppose with a days worth of work it could be done.

**Comment by koebi** [comment]
> Regarding: _if a layer contains a lot of points, the log gets rather long. could we add truncation to the geometry part in the log?_: I assume we are talking about the View'->'Panels'->'Log Messages' log? From the documentation it seems that this was intentionally kept to full length for debugging reasons. Should we add truncation anyways?

Yes, exactly.
If possible, it would be good if only the geometry could be truncated, such that you still have the original request, but your geometry looks like: 

`points: point1, point2, point3, …`

**Comment by Merydian** [comment]
Regarding: *May metadata requests when provider changes*, this is due to the temporal index being adapted. Isn't this a necessary step?

**Comment by koebi** [comment]
In general, yes.
It is something that shouldn't change too often, and that could be cached and updated once/day? It might be a bit of premature optimization though, I'm also fine with keeping it how it is currently and adding an issue (to then tackle later on, hopefully).

**Comment by mcauer** [comment]
> > > The branch [qgis-like-input](https://github.com/GIScience/ohsome-qgis-plugin/tree/qgis-like-input) solves: _The option to add multiple point or polygon layers seems a bit unnecessary and can be dropped_ by taking input by selecting a layer, as in any other QGis tool. This dismisses the existing _Centroids_ input option.
> > > What is the preferred option?
> > 
> > 
> > Is it possible to keep the Centroids-option and have all other layer inputs as QGIS usually does? If not, I'd like @mcauer and/or @joker234 to comment on this, since they have a better intuition on what will be more useful to our users.
> 
> I suppose with a days worth of work it could be done.

I would say it is worth to put some effort and keep interactive centroid option in addition to choose some layer input

**Comment by koebi** [comment]
fixed in #58
